### ISSUE TITLE
Not working with ionic crosswalk 14

### ISSUE THREAD

**Issue by piernik** [wf9a5m75/phonegap-googlemaps-plugin#520]
I'm tring to get Your plugin to work with ionic but no luck.
Here are commands

```
C:\strony\www\test_app>ionic run
Updated the hooks directory to have execute permissions
runCordova run
Running command: "C:\Program Files\nodejs\node.exe" C:\strony\www\test_app\hooks\after_prepare\010_add_platform_class
.js C:\strony\www\test_app
add to body class: platform-android
Running command: C:\strony\www\test_app\platforms\android\cordova\run.bat
ANDROID_HOME=C:\Users\Lukasz\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_40
WARNING : No target specified, deploying to device '192.168.56.101:5555'.
Running: C:\strony\www\test_app\platforms\android\gradlew cdvBuildDebug -b C:\strony\www\test_app\platforms\android\b
uild.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library] Current NDK support is deprecat
ed.  Alternative will be provided in the future.
:preBuild
:compileX86DebugNdk UP-TO-DATE
:preX86DebugBuild
:checkX86DebugManifest
:preArmv7DebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:compileLint
:com.google.playservices:PolskieSzlaki-google-play-services_lib:copyDebugLint UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:mergeDebugProguardFiles UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:preBuild
:com.google.playservices:PolskieSzlaki-google-play-services_lib:preDebugBuild
:com.google.playservices:PolskieSzlaki-google-play-services_lib:checkDebugManifest
:com.google.playservices:PolskieSzlaki-google-play-services_lib:preDebugTestBuild
:com.google.playservices:PolskieSzlaki-google-play-services_lib:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO
-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:prepareDebugDependencies
:com.google.playservices:PolskieSzlaki-google-play-services_lib:compileDebugAidl UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:compileDebugRenderscript UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:generateDebugBuildConfig UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:generateDebugAssets UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:mergeDebugAssets UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:generateDebugResValues UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:generateDebugResources UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:mergeDebugResources UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:processDebugManifest UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:processDebugResources UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:generateDebugSources UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:compileDebugJava UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:processDebugJavaRes UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:packageDebugJar UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:compileDebugNdk UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:packageDebugJniLibs UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:packageDebugLocalJar UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:packageDebugRenderscript UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:packageDebugResources UP-TO-DATE
:com.google.playservices:PolskieSzlaki-google-play-services_lib:bundleDebug UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:compileLint
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:copyDebugLint UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:mergeDebugProguardFiles UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:preBuild
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:preDebugBuild
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:checkDebugManifest
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:preDebugTestBuild
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP
-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:prepareDebugDependencies
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:compileDebugAidl UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:compileDebugRenderscript UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:generateDebugBuildConfig UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:generateDebugAssets UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:mergeDebugAssets UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:generateDebugResValues UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:generateDebugResources UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:mergeDebugResources UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:processDebugManifest UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:processDebugResources UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:generateDebugSources UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:compileDebugJava UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:processDebugJavaRes UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:packageDebugJar UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:compileDebugNdk UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:packageDebugJniLibs UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:packageDebugLocalJar UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:packageDebugRenderscript UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:packageDebugResources UP-TO-DATE
:cordova-plugin-crosswalk-webview:testapp511215-xwalk_core_library:bundleDebug UP-TO-DATE
:prepareAndroidComGooglePlayservicesPolskieSzlakiGooglePlayServices_libUnspecifiedDebugLibrary UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareAndroidCordovaPluginCrosswalkWebviewTestapp511215Xwalk_core_libraryUnspecifiedDebugLibrary UP-TO-DATE
:prepareX86DebugDependencies
:compileX86DebugAidl UP-TO-DATE
:compileX86DebugRenderscript UP-TO-DATE
:generateX86DebugBuildConfig UP-TO-DATE
:generateX86DebugAssets UP-TO-DATE
:mergeX86DebugAssets UP-TO-DATE
:generateX86DebugResValues UP-TO-DATE
:generateX86DebugResources UP-TO-DATE
:mergeX86DebugResources UP-TO-DATE
:processX86DebugManifest UP-TO-DATE
:processX86DebugResources UP-TO-DATE
:generateX86DebugSources UP-TO-DATE
:compileX86DebugJavaC:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:138: error: canno
t find symbol
    root = (ViewGroup) webView.getParent();
                              ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:197: error: cannot find symbol
          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
                 ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:206: error: cannot find symbol
          webView.setBackgroundColor(0);
                 ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:789: error: cannot find symbol
    webView.setVisibility(View.GONE);
           ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:807: error: cannot find symbol
        webView.setVisibility(View.VISIBLE);
               ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:879: error: cannot find symbol
          divTop - webView.getScrollY(), 
                          ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\GoogleMaps.java:881: error: cannot find symbol
          divTop + divH - webView.getScrollY());
                                 ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:53: error: cannot find symbol
    this.root = (ViewGroup) webView.getParent();
                                   ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:55: error: cannot find symbol
    webView.setBackgroundColor(Color.TRANSPARENT);
           ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:57: error: cannot find symbol
      webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
             ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:132: error: cannot find symbol
    int scrollY = webView.getScrollY();
                         ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:180: error: incompatible types: C
ordovaWebView cannot be converted to View
    frontLayer.removeView(webView);
                          ^
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:191: error: incompatible types: C
ordovaWebView cannot be converted to View
    root.addView(webView);
                 ^
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                               ^
  symbol:   method getScrollX()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                                                     ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:214: error: no suitable method fo
und for removeView(CordovaWebView)
    root.removeView(webView);
        ^
    method ViewManager.removeView(View) is not applicable
      (argument mismatch; CordovaWebView cannot be converted to View)
    method ViewGroup.removeView(View) is not applicable
      (argument mismatch; CordovaWebView cannot be converted to View)
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:221: error: incompatible types: C
ordovaWebView cannot be converted to View
    frontLayer.addView(webView);
                       ^
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:261: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:266: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:292: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
C:\strony\www\test_app\platforms\android\src\plugin\google\maps\MyPluginLayout.java:303: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
 FAILED
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
21 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileX86DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.956 secs

C:\strony\www\test_app\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\strony\www\test_app\platforms\android\gradlew cdvBuildDebug -b C:\
strony\www\test_app\platforms\android\build.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true"
ERROR running one or more of the platforms: Error: C:\strony\www\test_app\platforms\android\cordova\run.bat: Command
failed with exit code 1
You may not have the required environment or OS to run this project
```
Plugin list
```
C:\strony\www\test_app>ionic plugin list
Updated the hooks directory to have execute permissions
runCordova plugin
android.support.v4 21.0.1 "Android Support v4"
com.google.playservices 23.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-crosswalk-webview 1.0.1-dev "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.0.0 "Whitelist"
nl.x-services.plugins.toast 2.0.5 "Toast"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"
plugin.http.request 1.0.4 "phonegap-http-request"
```

Ionic uses `browser` option whidh adds crosswalk - http://ionicframework.com/docs/cli/browsers.html
How to fix this issue?

**Comment by Hirbod** [comment]
You can't use the cli for that. Canary is currently neccaseray for that.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)

**Comment by piernik** [comment]
I added crosswalk 14

**Comment by Hirbod** [comment]
You need minimum 14.42.329.0 or up. You need to follow the tutorial. You have to be on android-js 3.7 (not 4) nor Cordova 5.0

**Comment by piernik** [comment]
I have crosswalk 14.42.329.0 but I'm using cordova 5.0  so this is the issue.
Do You plan, if so when, support cordova 5?

**Comment by Hirbod** [comment]
It is in the roadmap but no ETA due to limited time. We're currently investigating

**Comment by piernik** [comment]
Can You post here ETA (few weeks, few months). Should I try with previous cordova version or maybe wait a few weeks?

**Comment by Hirbod** [comment]
There is not eta. Downgrade to 4.3.0, there are no big benefits using 5.0 right now. You can still work with the new Cordova 5.0 cli but you have to specify the correct platform, like "Cordova platform add android@3.7.0

**Comment by Hirbod** [comment]
The problem isn't the cli, it is the new android version which has some big changes in it's api

**Comment by piernik** [comment]
Ok I understand - thanks for help.

**Comment by piernik** [comment]
Using `ionic browser add crosswalk@14.42.334.0` updates platform to 4.0 so I have to wait.
As I am not `fluent`in cordova I hope You'll manage to update it within month;)

**Comment by Hirbod** [comment]
Just install it manually. I don't know why you are making such a big deal of it. There is a good migration documentation.

**Comment by piernik** [comment]
I'll try - thanks for help and for Your work.

**Comment by glemiere** [comment]
Java files used deprecated functions.
Use this plugin and it will work ;-)
https://github.com/Nipher/phonegap-googlemaps-plugin

**Comment by mabdelfattah** [comment]
@glemiere , I've just tried the fork you mentioned but I'm getting the same error!

**Comment by glemiere** [comment]
try npm -g install cordova@5.0.0

**Comment by mabdelfattah** [comment]
$ cordova -v                                                                                                      
    
    5.0.0

$ cordova run android
    
    :compileX86DebugJava
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:69: error: cannot find symbol
    import com.google.android.gms.location.LocationSettingsRequest;
                                          ^
      symbol:   class LocationSettingsRequest
      location: package com.google.android.gms.location
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:70: error: cannot find symbol
    import com.google.android.gms.location.LocationSettingsResult;
                                          ^
      symbol:   class LocationSettingsResult
      location: package com.google.android.gms.location
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:71: error: cannot find symbol
    import com.google.android.gms.location.LocationSettingsStatusCodes;
                                          ^
      symbol:   class LocationSettingsStatusCodes
      location: package com.google.android.gms.location
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:86: error: cannot find symbol
    import com.google.android.gms.maps.OnMapReadyCallback;
                                      ^
      symbol:   class OnMapReadyCallback
      location: package com.google.android.gms.maps
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:549: error: cannot find symbol
        mapView.getMapAsync(new OnMapReadyCallback() {
                                ^
      symbol:   class OnMapReadyCallback
      location: class GoogleMaps
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:992: error: package LocationSettingsRequest does not exist
        LocationSettingsRequest.Builder builder = new LocationSettingsRequest.Builder();
                               ^
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:992: error: package LocationSettingsRequest does not exist
        LocationSettingsRequest.Builder builder = new LocationSettingsRequest.Builder();
                                                                             ^
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1005: error: cannot find symbol
        PendingResult<LocationSettingsResult> locationSettingsResult =
                      ^
      symbol:   class LocationSettingsResult
      location: class GoogleMaps
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1006: error: cannot find symbol
            LocationServices.SettingsApi.checkLocationSettings(googleApiClient, builder.build());
                            ^
      symbol:   variable SettingsApi
      location: class LocationServices
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1008: error: cannot find symbol
        locationSettingsResult.setResultCallback(new ResultCallback<LocationSettingsResult>() {
                                                                    ^
      symbol:   class LocationSettingsResult
      location: class GoogleMaps
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1011: error: cannot find symbol
          public void onResult(LocationSettingsResult result) {
                               ^
      symbol: class LocationSettingsResult
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1014: error: cannot find symbol
              case LocationSettingsStatusCodes.SUCCESS:
                   ^
      symbol: variable LocationSettingsStatusCodes
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1018: error: cannot find symbol
              case LocationSettingsStatusCodes.RESOLUTION_REQUIRED:
                   ^
      symbol: variable LocationSettingsStatusCodes
    /Users/user/app/platforms/android/src/plugin/google/maps/GoogleMaps.java:1042: error: cannot find symbol
              case LocationSettingsStatusCodes.SETTINGS_CHANGE_UNAVAILABLE:
                   ^
      symbol: variable LocationSettingsStatusCodes
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    14 errors
    :compileX86DebugJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileX86DebugJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 14.075 secs

**Comment by glemiere** [comment]
What is your SDK version ?

**Comment by mabdelfattah** [comment]
@glemiere, here are the cordova plugins

    com.google.playservices 18.0.0 "Google Play Services for Android"
    com.googlemaps.ios 1.9.2 "Google Map iOS SDK for Cordova"
    cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
    cordova-plugin-device 1.0.1 "Device"
    cordova-plugin-dialogs 1.1.1 "Notification"
    cordova-plugin-geolocation 1.0.1 "Geolocation"
    cordova-plugin-globalization 1.0.1 "Globalization"
    cordova-plugin-google-analytics 0.8.0 "Google Universal Analytics Plugin"
    cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
    cordova-plugin-network-information 1.0.1 "Network Information"
    nl.x-services.plugins.launchmyapp 3.2.4 "Custom URL scheme"
    plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"
    plugin.http.request 1.0.4 "phonegap-http-request"
