### PR TITLE
Cordova 5.0.0

### PR DESCRIPTION
**Pull request by Nipher**
Missing changes

### CODE REVIEW

**Comment by Hirbod** [comment]
Could you compile successful and see a working map on Cordova 5.0.0 ?

**Comment by Hirbod** [comment]
And please submit to #test branch

**Comment by Nipher** [comment]
Sorry, wasn't my intention to open this pull request, I was working with my friend to run the plugin on Cordova 5.0,  but we didn't test it well enough yet...
When we make sure that everything it's ok I would be happy to submit it to the test branch!
Thanks

**Comment by Hirbod** [comment]
allright!

**Comment by piernik** [comment]
@Nipher how tests go on?

**Comment by Nipher** [comment]
Hi, I didn't test much, but I could compile successful and see a working map on Cordova 5.0.0,
We (me and @Phenome ) commented this line:
```import org.apache.cordova.ScrollEvent;```

And  we commented out the ```onEvent``` processing, that seemingly processes only scroll events...

And we are using the ```getView``` method, 
example: ```webView.getView().setBackgroundColor(0);```
https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebView.java#L40

I added the plugin from my rep, and it worked..
```cordova plugin add https://github.com/Nipher/phonegap-googlemaps-plugin.git```

The latest commit that I tested was:
Nipher/phonegap-googlemaps-plugin@2e56ba3d93fd07bb9c1036ed0508232503f6f08c
I didn't commit anything else yet though...

**Comment by piernik** [comment]
Thanks @Nipher I'll test it day after tommorow and give feedback

**Comment by mirko77** [comment]
Well done guys! @piernik let us know how it goes, I might have some time to test it as well during this week

**Comment by Nipher** [comment]
Great! Thank you guys, let me know if I should do something else or if there is something wrong...
@Hirbod 
Should I open a new pull request with the latest commit to the test branch?

**Comment by piernik** [comment]
I can confirm that Your version works well with cordova 5.0 - thank You vary much - great!!

**Comment by piernik** [comment]
@Nipher I have one problem.
After opening map default controllers (zoom in out and gps) are disapearing though they are still there (tapping on a blank space do proper action).

**Comment by Hirbod** [comment]
@wf9a5m75

**Comment by wf9a5m75** [comment]
I will test this later.

**Comment by cosmith** [comment]
Works for me too, with the same little issue that @piernik pointed out. Thanks!

**Comment by Davide95** [comment]
I've the same problem of @piernik too

**Comment by designed-in-india** [comment]
Same issue here. Would the fix from @Phenome fixes all issues?

**Comment by pallu87** [comment]
C:\tmp\HelloMap>cordova build android
Running command: C:\tmp\HelloMap\platforms\android\cordova\build.bat
ANDROID_HOME=C:\Users\PANA\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_05
Running: C:\tmp\HelloMap\platforms\android\gradlew cdvBuildDebug -b C:\tmp\Hello
Map\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:compileLint
:com.google.playservices:myapp-google-play-services_lib:copyDebugLint UP-TO-DATE

:com.google.playservices:myapp-google-play-services_lib:mergeDebugProguardFiles
                                                                               U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:preBuild
:com.google.playservices:myapp-google-play-services_lib:preDebugBuild
:com.google.playservices:myapp-google-play-services_lib:checkDebugManifest
:com.google.playservices:myapp-google-play-services_lib:preDebugTestBuild
:com.google.playservices:myapp-google-play-services_lib:prepareAndroidCordovaLib
UnspecifiedDebugLibrary                                                        U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:prepareDebugDependencies

:com.google.playservices:myapp-google-play-services_lib:compileDebugAidl UP-TO-D
ATE
:com.google.playservices:myapp-google-play-services_lib:compileDebugRenderscript
                                                                               U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:generateDebugBuildConfig
                                                                               U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:generateDebugAssets UP-T
O-DATE
:com.google.playservices:myapp-google-play-services_lib:mergeDebugAssets UP-TO-D
ATE
:com.google.playservices:myapp-google-play-services_lib:generateDebugResValues U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:generateDebugResources U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:mergeDebugResources UP-T
O-DATE
:com.google.playservices:myapp-google-play-services_lib:processDebugManifest UP-
TO-DATE
:com.google.playservices:myapp-google-play-services_lib:processDebugResources UP
-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:generateDebugSources UP-
TO-DATE
:com.google.playservices:myapp-google-play-services_lib:compileDebugJava UP-TO-D
ATE
:com.google.playservices:myapp-google-play-services_lib:processDebugJavaRes UP-T
O-DATE
:com.google.playservices:myapp-google-play-services_lib:packageDebugJar UP-TO-DA
TE
:com.google.playservices:myapp-google-play-services_lib:compileDebugNdk UP-TO-DA
TE
:com.google.playservices:myapp-google-play-services_lib:packageDebugJniLibs UP-T
O-DATE
:com.google.playservices:myapp-google-play-services_lib:packageDebugLocalJar UP-
TO-DATE
:com.google.playservices:myapp-google-play-services_lib:packageDebugRenderscript
                                                                               U
P-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:packageDebugResources UP
-TO-DATE
:com.google.playservices:myapp-google-play-services_lib:bundleDebug UP-TO-DATE
:prepareAndroidComGooglePlayservicesMyappGooglePlayServices_libUnspecifiedDebugL
ibrary                                                                         U
P-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources
C:\tmp\HelloMap\platforms\android\build\intermediates\res\debug\xml\config.xml:2
9: error: Error parsing XML: unbound prefix

:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\PANA\AppData\Local\Android\android-sdk\build-tools\21.1.2\aapt.
exe package -f --no-crunch -I C:\Users\PANA\AppData\Local\Android\android-sdk\pl
atforms\android-21\android.jar -M C:\tmp\HelloMap\platforms\android\build\interm
ediates\manifests\full\debug\AndroidManifest.xml -S C:\tmp\HelloMap\platforms\an
droid\build\intermediates\res\debug -A C:\tmp\HelloMap\platforms\android\build\i
ntermediates\assets\debug -m -J C:\tmp\HelloMap\platforms\android\build\generate
d\source\r\debug -F C:\tmp\HelloMap\platforms\android\build\intermediates\res\re
sources-debug.ap_ --debug-mode --custom-package com.example.myapp -0 apk --outpu
t-text-symbols C:\tmp\HelloMap\platforms\android\build\intermediates\symbols\deb
ug
Error Code:
        1
Output:
        C:\tmp\HelloMap\platforms\android\build\intermediates\res\debug\xml\conf
ig.xml:29: error: Error parsing XML: unbound prefix



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 18.634 secs

C:\tmp\HelloMap\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\tmp\HelloMap\platforms\androi
d\gradlew cdvBuildDebug -b C:\tmp\HelloMap\platforms\android\build.gradle -Dorg.
gradle.daemon=true"
ERROR building one of the platforms: Error: C:\tmp\HelloMap\platforms\android\co
rdova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: C:\tmp\HelloMap\platforms\android\cordova\build.bat: Command failed with
exit code 8
    at ChildProcess.whenDone (C:\Users\PANA\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

C:\tmp\HelloMap>

Line 29 is :  
```xml
<vs:plugin name="plugin.google.maps">
        <param name="API_KEY_FOR_ANDROID" value="###MANUALLY REPLACED FOR COMMENT ##" />
        <param name="API_KEY_FOR_IOS" value="###MANUALLY REPLACED FOR COMMENT ##" />
    </vs:plugin>
```

The File at 'C:\tmp\HelloMap\platforms\android\build\intermediates\res\debug\xml' is ...
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.example.myapp" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <preference name="loglevel" value="DEBUG" />
    <feature name="Whitelist">
        <param name="android-package" value="org.apache.cordova.whitelist.WhitelistPlugin" />
        <param name="onload" value="true" />
    </feature>
    <feature name="HttpRequest">
        <param name="android-package" value="plugin.http.request.HttpRequest" />
    </feature>
    <feature name="GoogleMaps">
        <param name="android-package" value="plugin.google.maps.GoogleMaps" />
    </feature>
    <feature name="External">
        <param name="android-package" value="plugin.google.maps.External" />
    </feature>
    <feature name="Geocoder">
        <param name="android-package" value="plugin.google.maps.MyGeocoder" />
    </feature>
    <allow-intent href="market:*" />
    <name>HelloMap</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <vs:plugin name="plugin.google.maps">
        <param name="API_KEY_FOR_ANDROID" value="###MANUALLY REPLACED FOR COMMENT ##" />
        <param name="API_KEY_FOR_IOS" value="###MANUALLY REPLACED FOR COMMENT ##" />
    </vs:plugin>
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="android-minSdkVersion" value="18" />
    <preference name="android-targetSdkVersion" value="21" />
</widget>
<!-- From: file:/C:/tmp/HelloMap/platforms/android/res/xml/config.xml -->
```

**Comment by piernik** [comment]
@wf9a5m75 I know that You are very bussy but can You give it a look and fix Your plugin to work with cordova 5.0? It would be great.

**Comment by pallu87** [comment]
Hello Guys, Is there a plan to continue development of this plugin ? if not, can you guys suggest any other plugin which would allow a native map to be displayed. I already tried Angular Maps and its very slow.

**Comment by fgarzonhz** [comment]
If you want to use under cordova 5 you an check:  https://github.com/Nipher/phonegap-googlemaps-plugin this works for us.


Franklin Garzón
  
*Lucha hasta alcanzar tus sueños*


 
 Date: Wed, 17 Jun 2015 06:21:17 -0700

**Comment by leandro-shifteight** [comment]
I am having #537 issue with @Nipher fork but was warking before with the master here.

**Comment by alexislg2** [comment]
This PR is not working for me:

```
/home/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:53: error: cannot find symbol
    this.root = (ViewGroup) webView.getParent();
                                   ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
/home/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:261: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
/home/alexis/mafia/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:138: error: cannot find symbol
    root = (ViewGroup) webView.getParent();
                              ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/alexis/mafia/cordova/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by Hirbod** [comment]
@Nipher 
I can comfirm: this version is not working. Tested with the current stable Cordova and Android release.

**Comment by Hirbod** [comment]
The master is up to date now! And works well with the new cordova!

**Comment by cosmith** [comment]
:+1:
