### ISSUE TITLE
BUILD Workaround for Android Cordova  5.1.1

### ISSUE THREAD

**Issue by Juelcf** [wf9a5m75/phonegap-googlemaps-plugin#576]
Hi,

I found a workaround that worked for me to build with cordova 5.1.1.

Error:
<b>GoogleMaps.java:15: error: cannot find symbol import org.apache.cordova.ScrollEvent;</b>

Solution: 

Just add the <b>ScrollEvent.java</b> to the folder <b>app\platforms\android\src\org\apache\cordova</b>

Source: <b>https://raw.githubusercontent.com/apache/cordova-amazon-fireos/master/framework/src/org/apache/cordova/ScrollEvent.java</b>

-----

Error:
<b>GoogleMaps.java:135: error: cannot find symbol root = (ViewGroup) webView.getParent();</b> ....
and
<b>MyPluginLayout.java:53: error: cannot find symbol this.root = (ViewGroup) webView.getParent(); </b>....

For this one we need to change the <b>webView.getParent();</b> to <b>webView.getView().getParent();</b>

Same for all the next errors regarding the webView.

I included the full changed files in pastebin. Just replace the old ones with this ones.

Folder: <b>app\platforms\android\src\plugin\google\maps</b>

GoogleMaps.java -> http://pastebin.com/raw.php?i=P7ctVbd6
MyPluginLayout.java -> http://pastebin.com/raw.php?i=YPE8ndPc

Thats all!

Then just run: <b>cordova build android</b>

** BUILD SUCCESSFUL :+1: 

;)

Have fun! :smile:

**Comment by Marthunder** [comment]
Hi !
Thanks for this issue works for me !

**Comment by jlopezmartinez** [comment]
Thank you works perfectly!!!!!!!!!

**Comment by Hirbod** [comment]
This is not a real solution, more a workaround. But thanks for sharing!

**Comment by grigored** [comment]
Tried the fix, but the app crashes on map loading. No message gets written in the console.

**Comment by bumerang07** [comment]
Hi,
thank you for your solution, but be aware i does not work with corodova: 5.2.0

**Comment by jvence** [comment]
Does this work with the latest version of the plugin: plugin.google.maps 1.2.5 "phonegap-googlemaps-plugin"?

Followed instructions but getting a bunch of errors:

/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:198: error: cannot find symbol
          webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
                 ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:207: error: cannot find symbol
          webView.setBackgroundColor(0);
                 ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:790: error: cannot find symbol
    webView.setVisibility(View.GONE);
           ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:808: error: cannot find symbol
        webView.setVisibility(View.VISIBLE);
               ^
  symbol:   method setVisibility(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:880: error: cannot find symbol
          divTop - webView.getScrollY(), 
                          ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java:882: error: cannot find symbol
          divTop + divH - webView.getScrollY());
                                 ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:55: error: cannot find symbol
    webView.setBackgroundColor(Color.TRANSPARENT);
           ^
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:57: error: cannot find symbol
      webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
             ^
  symbol:   method setLayerType(int,<null>)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:132: error: cannot find symbol
    int scrollY = webView.getScrollY();
                         ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:180: error: incompatible types: CordovaWebView cannot be converted to View
    frontLayer.removeView(webView);
                          ^
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:191: error: incompatible types: CordovaWebView cannot be converted to View
    root.addView(webView);
                 ^
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                               ^
  symbol:   method getScrollX()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:200: error: cannot find symbol
    scrollView.scrollTo(webView.getScrollX(), webView.getScrollY());
                                                     ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:214: error: no suitable method found for removeView(CordovaWebView)
    root.removeView(webView);
        ^
    method ViewManager.removeView(View) is not applicable
      (argument mismatch; CordovaWebView cannot be converted to View)
    method ViewGroup.removeView(View) is not applicable
      (argument mismatch; CordovaWebView cannot be converted to View)
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:221: error: incompatible types: CordovaWebView cannot be converted to View
    frontLayer.addView(webView);
                       ^
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:261: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:266: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:292: error: cannot find symbol
        webView.requestFocus(View.FOCUS_DOWN);
               ^
  symbol:   method requestFocus(int)
  location: variable webView of type CordovaWebView
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java:303: error: cannot find symbol
      int scrollY = webView.getScrollY();
                           ^
  symbol:   method getScrollY()
  location: variable webView of type CordovaWebView

**Comment by alexbarnsley** [comment]
@jvence you have to do **.getView()** after each occurrence of **webView**. Make sure you're editing the correct files as @Juelcf's original post worked perfectly for me. The files based on your errors:

/dev/project/test/cordova/platforms/android/src/plugin/google/maps/GoogleMaps.java
/dev/project/test/cordova/platforms/android/src/plugin/google/maps/MyPluginLayout.java

**Comment by Hirbod** [comment]
1.2.7 is out and works for cordova-android 4.x and cordova 5.x

**Comment by diaspar** [comment]
@Hirbod This does not seems to work:

cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin.git#1.2.7

Is the tag released?

**Comment by Hirbod** [comment]
use #master

**Comment by Hirbod** [comment]
use #master

**Comment by Hirbod** [comment]
Update: I've just released 1.2.7

I will incorporate some other fixes these days (like the base64 bug etc) and will push out 1.2.8 soon

**Comment by diaspar** [comment]
@Hirbod thanks, works on the IOS simulator. I hope you update the registry soon

**Comment by Hirbod** [comment]
@diaspar iOS is not related here. This update just had changes for android
