### ISSUE TITLE
[Bounty Request] Support current versions of Ionic / Cordova / CrossWalk [$65]

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#536]
Hello,

There is a lots of problems with last versions of Ionic / Cordova / CrossWalk for this plugin.

The current stable versions : 
- Ionic 1.4.5
- Cordova 5.0
- CrossWalk is 12.41.296.5

( For information, the Nipher fork permit to compile and run, but I have a black map with random crash )

I propose to create a bounty for this "feature", and permit to any developper to help to this great plugin to continue to exists.

Regards,

**Comment by alexlt** [comment]
Good idea, I also have this black map issue with the Nipher fork

**Comment by alexislg2** [comment]
Just added a $15 bounty. Really looking forward for this compatibility.

**Comment by lakano** [comment]
Thanks @alexislg2 
I hope a lot of others supporters could also participate to help every users of this plugin !

**Comment by fujunwei** [comment]
Could you please try to use Crosswalk-14 in the cordova crosswalk plugin. You can try out the version using a `<preference>` tag within your config.xml 
`<preference name="xwalkVersion" value="14+" />`

**Comment by Honry** [comment]
I can also reproduce this issue with 
* [cordova-plugin-crosswalk-webview](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) with Crosswalk-14(14.43.343.12) or Crosswalk-13
* [phonegap-googlemaps-plugin](https://github.com/Nipher/phonegap-googlemaps-plugin) from Nipher
* test from [cordova-mobile-spec](https://github.com/apache/cordova-mobile-spec): Plugin Tests(Automatic and Manual)->Manual Tests->org.apache.cordova.mobilespec.thirdpartytests.thirdparty.tests->Show Map.
* Screenshot:
![screenshot_2015-06-10-16-51-37](https://cloud.githubusercontent.com/assets/3271201/8078798/b1da16e8-0f92-11e5-9813-71b6b81c220c.png)

I suppose it is a matter from crosswalk since the black screen disappeared after removing the crosswalk webview plugin, I will push this issue to crosswalk team later on.

**Comment by Honry** [comment]
https://crosswalk-project.org/jira/browse/XWALK-4372

**Comment by masashiGMS** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)

**Comment by lakano** [comment]
Ok, so the problem can't be solved in current stable version of Crosswalk, we need to use the beta version. I'll try, thanks @masashiGMS

**Comment by Honry** [comment]
All, the developer(@fujunwei)  from crosswalk provided the solution and I had verified it. 

Meanwhile, I drafted a wiki for using crosswalk webview plugin in googlemaps plugin, https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-(Android)
Anyone can help review/try? I hope it can be merged into https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)

**Comment by lakano** [comment]
@Honry : Thanks ! This working fine :-)
I'll give you my bounty part.

@masashiGMS : This tutorial was the old one, and don't works with Cordova 5.0 or last CrossWalk ( the code was changed, but  @Honry have explained how to fix that )

Regards,

**Comment by Honry** [comment]
Thanks @lakano, but I think the bounty should belong to @fujunwei who provided the solution, and I just do the work of reproduction.

**Comment by lakano** [comment]
Ok @Honry 
@masashiGMS : Could you reclaim the bounty to get the money ? regards

**Comment by fujunwei** [comment]
Thanks @Honry ,  Let's share it.

**Comment by wf9a5m75** [comment]
@Honry Did you receive any amount from bountysource?

**Comment by lakano** [comment]
@Honry / @fujunwei : You need to claim the bounty on the link :
https://www.bountysource.com/issues/20138867-bounty-request-support-current-versions-of-ionic-cordova-crosswalk-65/developers

After that, I suppose I can confirm it. 
Thanks

**Comment by thim81** [comment]
Hi Honry,

We followed your drafted wiki page, which was very helpful.
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-Webview-Plugin-(Android)

But we still can't get it to work.

The compiler complains about

` platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java error: cannot find symbol setZOrderOnTop`

What could be the reason?

Some extra info about the setup we are using:
* Cordova 5.0.0
* Nipher fork of phonegap-googlemaps-plugin
* Ionic 1.5.1

We tried with:
* Crosswalk (beta)Version 13.42.319.6 Published Tue Apr 14 2015 14:24:00 GMT+0200 (CEST)
* Crosswalk (canary) Version 14.42.334.0 Published Mon Apr 13 2015 09:16:00 GMT+0200 (CEST)

Are we missing something?

We are willing to chip in for the bounty since this is very important for us to get it sorted out soon.

Regards,
Tim

**Comment by Honry** [comment]
Could you please try Crosswalk (beta) 14+ ? Or if there are more error log would be helpful.

**Comment by thim81** [comment]
Hi Honry,

We followed your advice and your tutorial again and made it work on.

Stack used:
* Cordova 5.0.0
* Nipher fork of phonegap-googlemaps-plugin
* Ionic 1.0.1 (vanadium-vaquita)
* Crosswalk (canary) Version 14.42.334.0 

For all Ionic users we want to share our steps that we followed to get this working:

### 0. Requirement
```bash
$> npm install cordova -g
(Cordova CLI >= 5.0.0)
```

### 1. Create a project - Optional for existing projects
This step can be skipped for existing Ionic projects.
```bash
$> cordova create HelloMap com.example.myapp HelloMap
$> cd HelloMap & cordova platform add android
```

### 2. Add Crosswalk webview plugin
```bash
$> cordova plugin add cordova-plugin-crosswalk-webview
```

or
```bash
$> ionic browser add crosswalk
```

The phonegap-googlemaps-plugin **requires the latest Crosswalk 14+ browser**, to have a proper functioning googlemaps plugin.

So make sure you use the latest browser, depending on your list of available browsers.
Specifying a version
```bash
$> ionic browser add crosswalk@14.42.334.0
```
Where you replace the number after the **@** with the version in your browser list.
```bash
$> ionic browser list 
```
This should show all the browsers available by platform.

You can refer to https://www.npmjs.com/package/cordova-plugin-crosswalk-webview#configure to configure Crosswalk version.

### 3. Obtain the Google Maps API Key for Android - Optional for existing projects
Nothing changes here for existing projects.

* Find the **keytool**.
 * OS X and Linux: ~/.android/

*Display the SHA-1 fingerprint
```bash
keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
```
![img](https://googledrive.com/host/0B1ECfqTCcLE8SkNKNnJNS1BEQk0/android_keystore.png)

* Go to [Google APIs Console](https://code.google.com/apis/console/).
* Register your project
* Turn on **Google Maps Android API v2**
* Go to **API Access** page.
* Click [Create New Android Key] button
* In the resulting dialog, enter the SHA-1 fingerprint, then a semicolon, then your application's package name.
* Write down the API Key
See [the official document: Get an Android certificate and the Google Maps API key]

![](https://googledrive.com/host/0B1ECfqTCcLE8SkNKNnJNS1BEQk0/api_console.png)

![img](https://googledrive.com/host/0B1ECfqTCcLE8SkNKNnJNS1BEQk0/api_key.png)

### 4. Install this plugin
For Ionic users, we can suggest the Phonegap-googlemaps-plugin Nipher fork since this currently offers support for Cordova 5.0 (which will be merged in the future release of the phonegap-googlemaps-plugin)
```bash
$> cd HelloMap/
$> cordova plugin add https://github.com/Nipher/phonegap-googlemaps-plugin --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE"
```

### 5. Change the AndroidManifest.xml, config.xml, MainActivity.java and XWalkWebViewEngine.java

In order to change the background color of the WebView as transparent, you need to modify the application settings **by your hand**.

Open `AndroidManifest.xml`, find `android:theme="@android:style/Theme.Black.NoTitleBar"`, then change to `android:theme="@android:style/Theme.Translucent.NoTitleBar"`.
![](https://googledrive.com/host/0B1ECfqTCcLE8flR3QTBESkJQUnNRMXpyclZkdkJqVTJRSW1kVWg2QXZxYUpIS2JzTFBIUWs/change_theme.png)


After that, open `HelloMap/platforms/android/src/com/example/map/MainActivity.java`, then add the following two lines. Where "HelloMap" and "Example" are variables that represent the name of your Ionic project.
```java
import org.xwalk.core.XWalkPreferences;  // <!-- Add this line

public class MainActivity extends CordovaActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, false);  // <!-- Add this line
        super.onCreate(savedInstanceState);
        // Set by <content src="index.html" /> in config.xml
        loadUrl(launchUrl);
    }
}
```

And then, open `HelloMap/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java`, then add the following line. Where "HelloMap" is the name of your Ionic project.

```java

    private void initWebViewSettings() {
        webView.setVerticalScrollBarEnabled(false);
        webView.setZOrderOnTop(true);  // <!-- Add this line
    }

```

Edit config.xml (root project folder) add this line:
```xml
<preference name="xwalkVersion" value="14+"/>
```

### 6. Check the HelloMap/www/index.html - Optional for existing projects
Nothing changes here for existing projects.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript">
    var map;
    document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");

      // Initialize the map view
      map = plugin.google.maps.Map.getMap(div);

      // Wait until the map is ready status.
      map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);
    }, false);

    function onMapReady() {
      var button = document.getElementById("button");
      button.addEventListener("click", onBtnClicked, false);
    }

    function onBtnClicked() {
      map.showDialog();
    }
    </script>
  </head>
  <body>
    <h3>PhoneGap-GoogleMaps-Plugin</h3>
    <div style="width:100%;height:400px" id="map_canvas"></div>
    <button id="button">Full Screen</button>
  </body>
</html>
```

### 7. Build and Run
For Android, just type these commands:
```bash
$> cd HelloMap/
$> ./cordova/run android
```
Where "HelloMap" is a variable that represent the name of your Ionic project.

**Comment by thim81** [comment]
@Honry: Big shoutout and thanks for the help! 
How can I thank you for your support and assistance?

**Comment by Honry** [comment]
Awesome! @thim81 
I come from Crosswalk, its my pleasure to make it work with this great plugin, and I am so glad to see you use Crosswalk and your problem finally got resolved!

**Comment by thim81** [comment]
Hi Honry,


We were using Ionic and Crosswalk and for some reason we now always get this error.
While nothing has changed with regards to Crosswalk, but suddenly we get complaints about a missing 
import org.xwalk.core.internal.XWalkCookieManager

## Error output
```
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:22: error: cannot find symbol
import org.xwalk.core.internal.XWalkCookieManager;
                              ^
  symbol:   class XWalkCookieManager
  location: package org.xwalk.core.internal
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:26: error: cannot find symbol
    protected XWalkCookieManager cookieManager = null;
              ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:29: error: cannot find symbol
        cookieManager = new XWalkCookieManager();
                            ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.
```

## Stack used:
- Cordova CLI: 5.0.0
- Ionic Version: 1.0.1
- Ionic CLI Version: 1.6.1
- Ionic App Lib Version: 0.3.3
- Crosswalk "version": "14.42.334.0"

**Comment by Honry** [comment]
I guess you are trying the latest webview plugin, this is caused by recently commit https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/34, and relative fix has been porting to Crosswalk 13 and Crosswalk 14 branch.
you can refer to the issue https://crosswalk-project.org/jira/browse/XWALK-4568, and you can wait for new beta version or trying the latest canary version.

**Comment by thim81** [comment]
Hi Honry,

Again you saved us, with your spot on support.

We applied to the fix like you referenced: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/pull/34 which solved the issue immediately.

For our interest , can you tell us how that the 
```
<preference name="xwalkVersion" value="14+"/>
```

Causes the webview plugin to update automatically? 
And how can we prevent this by locking it to a certain version?

**Comment by Honry** [comment]
With this preference, webview plugin will automatically fetch the latest Crosswalk beta 14 from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library_beta/ which is the place of latest Crosswalk beta version release.
You can try latest webview plugin from https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview when you use latest Crosswalk or if you have any issue on Crosswalk you can report it to https://crosswalk-project.org/jira/browse, then you will get fix very soon.

**Comment by thim81** [comment]
Hi Honry,

Would setting the Xwalkversion to 14 instead of 14+ prevent this from happening and still have the  webView.setZOrderOnTop(true) option? Because for us the current version is stable enough to continue working on it.

```
<preference name="xwalkVersion" value="14"/>
```
instead of
```
<preference name="xwalkVersion" value="14+"/>
```

**Comment by Honry** [comment]
No, they are equivalent, you can specify a fixed version, such as <preference name="xwalkVersion" value="14.43.343.18"/>. Then your crosswalk will not be automatically updated any more.

**Comment by thim81** [comment]
Hi Honry,

We have for now pinned the Xwalkversion to "14.43.343.18".
To prevent unexpected bugs due to new updates/features.

Once the 14 release is stable, we will update to the latest stable again.

Again big shoutout for your help and assistance.

Regards,
Tim

**Comment by lakano** [comment]
Hello everybody,

@thim81 How have you do to get the 14.43.343.18 version please ?

I don't see it in my browsers options : 
```
% ionic browser list
iOS - Browsers Listing:

Not Available Yet - WKWebView
Not Available Yet - UIWebView


Android - Browsers Listing:


Available - Crosswalk - ionic browser add crosswalk
	 Version 8.37.189.14 Published Fri Oct 10 2014 03:26:00 GMT+0200 (CEST)
	 Version 9.38.208.10 Published Tue Nov 25 2014 11:45:00 GMT+0100 (CET)
	 Version 10.39.235.15 Published Wed Dec 31 2014 13:16:00 GMT+0100 (CET)
	 Version 11.40.277.7 Published Thu Feb 26 2015 07:03:00 GMT+0100 (CET)
	 Version 12.41.296.5 Published Thu Mar 05 2015 13:19:00 GMT+0100 (CET)
(beta)	 Version 13.42.319.6 Published Tue Apr 14 2015 14:24:00 GMT+0200 (CEST)
(canary) Version 14.42.334.0 Published Mon Apr 13 2015 09:16:00 GMT+0200 (CEST)

Available - Crosswalk-lite - ionic browser add crosswalk-lite
(canary) Version 10.39.234.1 Published Fri Mar 06 2015 03:06:00 GMT+0100 (CET)
(canary) Version 10.39.236.1 Published Wed May 27 2015 02:54:00 GMT+0200 (CEST)

Available - Browser (default) - ionic browser revert android
Not Available Yet - GeckoView
```

I need to re-install from scratch all my plugins and have the XWalkCookie error :-/

BTW, Thanks @Honry for all your help on Crosswalk & this plugin !

**Comment by Honry** [comment]
You can try out a different Crosswalk version using a <preference> tag within your config.xml. e.g. ```<preference name="xwalkVersion" value="14.43.343.18"/>```(Currently only support Crosswalk beta and stable config), then the Crosswalk webview plugin will fetch the corresponding version of Crosswalk Runtime lib during app building.

You can also refer to https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/README.md#configure

**Comment by lakano** [comment]
Thanks @Honry for your help but this doens't works for me :-/ 

Cordova 5.1.1
Ionic 1.6.1

after creating the project : 
````
% ionic browser add crosswalk@14.43.343.18
Adding crosswalk browser
*Info*
Cordova CLI v5.0 no longer requires you to use the ionic browser command to get Crosswalk installed
The ionic browser command will install Cordova Android, the Crosswalk plugin, the whitelist plugin, and the splashscreen plugin for your convenience.
Due to this, if you need to specify a version of Crosswalk, see this link: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#configure
Enjoy! :)
Added Android
Added Crosswalk plugin
Added whitelist plugin
Added splash screen plugin
Completed installing Crosswalk
````

Then I add the plugin (Nipher fork), update the files ( crosswalk files, my android src files, config.xml, index.html )

And when I try to build : 
```
% ionic build android
Running command: /www/app/hooks/after_prepare/010_add_platform_class.js /www/app
add to body class: platform-android
Running command: /www/app/platforms/android/cordova/build 
ANDROID_HOME=/opt/android/
JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64/
Running: /www/app/platforms/android/gradlew cdvBuildDebug -b /www/app/platforms/android/build.gradle -Dorg.gradle.daemon=true
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
:preBuild
:compileArmv7DebugNdk
:preArmv7DebugBuild
:checkArmv7DebugManifest
:preX86DebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preArmv7ReleaseBuild
:preX86ReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportAppcompatV72200Library
:prepareComAndroidSupportMediarouterV72200Library
:prepareComAndroidSupportSupportV42200Library
:prepareComGoogleAndroidGmsPlayServices750Library
:prepareComGoogleAndroidGmsPlayServicesAds750Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics750Library
:prepareComGoogleAndroidGmsPlayServicesAppindexing750Library
:prepareComGoogleAndroidGmsPlayServicesAppinvite750Library
:prepareComGoogleAndroidGmsPlayServicesAppstate750Library
:prepareComGoogleAndroidGmsPlayServicesBase750Library
:prepareComGoogleAndroidGmsPlayServicesCast750Library
:prepareComGoogleAndroidGmsPlayServicesDrive750Library
:prepareComGoogleAndroidGmsPlayServicesFitness750Library
:prepareComGoogleAndroidGmsPlayServicesGames750Library
:prepareComGoogleAndroidGmsPlayServicesGcm750Library
:prepareComGoogleAndroidGmsPlayServicesIdentity750Library
:prepareComGoogleAndroidGmsPlayServicesLocation750Library
:prepareComGoogleAndroidGmsPlayServicesMaps750Library
:prepareComGoogleAndroidGmsPlayServicesNearby750Library
:prepareComGoogleAndroidGmsPlayServicesPanorama750Library
:prepareComGoogleAndroidGmsPlayServicesPlus750Library
:prepareComGoogleAndroidGmsPlayServicesSafetynet750Library
:prepareComGoogleAndroidGmsPlayServicesWallet750Library
:prepareComGoogleAndroidGmsPlayServicesWearable750Library
:prepareOrgXwalkXwalk_core_library_beta144334318Library
:prepareArmv7DebugDependencies
:compileArmv7DebugAidl
:compileArmv7DebugRenderscript
:generateArmv7DebugBuildConfig
:generateArmv7DebugAssets UP-TO-DATE
:mergeArmv7DebugAssets
:createXwalkCommandLineFileArmv7Debug
:generateArmv7DebugResValues
:generateArmv7DebugResources
:mergeArmv7DebugResources/www/app/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processArmv7DebugManifest
:processArmv7DebugResources
:generateArmv7DebugSources
:compileArmv7DebugJava/www/app/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:22: error: cannot find symbol
import org.xwalk.core.internal.XWalkCookieManager;
                              ^
  symbol:   class XWalkCookieManager
  location: package org.xwalk.core.internal
/www/app/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:26: error: cannot find symbol
    protected XWalkCookieManager cookieManager = null;
              ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
/www/app/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:29: error: cannot find symbol
        cookieManager = new XWalkCookieManager();
                            ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.855 secs

/www/app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /www/app/platforms/android/gradlew with args: cdvBuildDebug,-b,/www/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /www/app/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /www/app/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
```

In my config.xml I have set the exact version you proposed : 
```
   <preference name="xwalkVersion" value="14.43.343.18" />
```

Any idea ? :)

**Comment by Honry** [comment]
You encountered the same issue with @thim81, you can try 14.43.343.17 or use latest Crosswalk webview plugin from https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

**Comment by lakano** [comment]
Thanks agin @Honry , you're the man !

@thim81 : Be carefull, the version you have pinned is not the good one (.18) you need the (.17) 

Regards,
